/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    amenities: Amenity;
    packages: Package;
    faqs: Faq;
    testimonials: Testimonial;
    forms: Form;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and for when it fails to load. For a bird photo this is the species name.
   */
  alt: string;
  /**
   * Optional. Shown alongside the image where a layout allows it.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Every page on the site. Links point at these rather than at typed paths.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Used in the browser tab and as the page heading.
   */
  title: string;
  /**
   * The page's lead image. Leave it empty and the page shows none — the mirrored image is not kept as a fallback, so an empty field looks empty.
   */
  banner?: (number | null) | Media;
  /**
   * Sections this page builds from the CMS. Everything not listed here still comes from the mirrored markup, so a page with no blocks looks exactly as it did.
   */
  layout?:
    | (
        | {
            /**
             * The banner slides, in the order they should rotate.
             */
            slides: {
              /**
               * Fills the whole banner, cropped to fit. A wide photograph works best — a tall one will be cut off top and bottom.
               */
              image: number | Media;
              /**
               * The line of text over the photograph. Leave empty for a picture alone.
               */
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * The page's copy. Everything the mirrored page used to show in its content area is replaced by this.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * Which run of copy on the page this replaces.
             */
            target: 'home-intro' | 'home-about' | 'home-note' | 'home-cta';
            /**
             * Sits above the text. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The paragraphs themselves.
             */
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Optional. Shown as a small carousel beside the text, on the sections laid out in two halves.
             */
            images?: (number | Media)[] | null;
            showButton?: boolean | null;
            button?: {
              type?: ('reference' | 'custom') | null;
              /**
               * Leave empty to use the page's own menu name. Fill it in only to say something different here.
               */
              label?: string | null;
              reference?: (number | null) | Page;
              /**
               * Include the protocol, e.g. https://example.com/page.
               */
              url?: string | null;
              /**
               * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * Which list on the page this replaces.
             */
            target:
              | 'home-icons'
              | 'home-photos-1'
              | 'home-photos-2'
              | 'wfh-facilities'
              | 'wfh-activities'
              | 'premises-facilities';
            /**
             * Sits above the list. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The line under the heading — "Providing Hospitality the correct way".
             */
            subtitle?: string | null;
            display: 'icon-grid' | 'photo-grid' | 'list';
            /**
             * The photograph shown beside the list.
             */
            image?: (number | null) | Media;
            /**
             * What to list here, in the order it should appear.
             */
            items: (number | Amenity)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'amenities';
          }
        | {
            /**
             * Which run of cards on the page this replaces.
             */
            target: 'home-packages';
            /**
             * Sits above the cards. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The packages to show here, in the order they should appear.
             */
            items: (number | Package)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'packages';
          }
        | {
            /**
             * Which gallery on the page this replaces.
             */
            target: 'home-gallery';
            /**
             * Sits above the photographs. Leave empty for none.
             */
            heading?: string | null;
            display: 'carousel' | 'grid';
            /**
             * How many are visible at once on a desktop screen.
             */
            slidesToShow?: number | null;
            /**
             * The photographs, in the order they should appear.
             */
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Which logo strip on the page this replaces.
             */
            target: 'home-partners';
            /**
             * Sits above the logos. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The logos, in the order they should appear.
             */
            logos: {
              image: number | Media;
              /**
               * Not shown on the page. Used as the logo’s alt text.
               */
              name: string;
              /**
               * Optional. Where the logo links to, including https://.
               */
              url?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            /**
             * Sits above the reviews. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The reviews to show here, in the order they should appear.
             */
            items: (number | Testimonial)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Which form on the page this replaces.
             */
            target: 'home-enquiry';
            /**
             * Sits above the form. Leave empty for none.
             */
            heading?: string | null;
            /**
             * The form to show. Its questions are edited in Forms.
             */
            form: number | Form;
            /**
             * The heading in the half beside the form.
             */
            asideHeading?: string | null;
            /**
             * The copy under that heading.
             */
            asideBody?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            showAsideButton?: boolean | null;
            asideButton?: {
              type?: ('reference' | 'custom') | null;
              /**
               * Leave empty to use the page's own menu name. Fill it in only to say something different here.
               */
              label?: string | null;
              reference?: (number | null) | Page;
              /**
               * Include the protocol, e.g. https://example.com/page.
               */
              url?: string | null;
              /**
               * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
      )[]
    | null;
  /**
   * The path, without the leading slash. The home page is "home".
   */
  slug: string;
  /**
   * What menus call this page, when that differs from the title — "BIRDING GUIDES" for the team page. Every link to this page reads it, so changing it here changes it everywhere. Falls back to the title.
   */
  navLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Amenities, facilities and activities. A page picks which to show with an amenities block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  /**
   * What it is called on the site — "Hot Water", "Nature Walk".
   */
  label: string;
  /**
   * The picture shown above the label. Leave empty for items that only ever appear in a plain list.
   */
  icon?: (number | null) | Media;
  /**
   * Identifies this item in the page markup. Rarely needs changing.
   */
  slug: string;
  /**
   * The order they are listed in here. A block can still choose its own order for one page.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stays and tours. A page shows a set of them with a packages block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  /**
   * The paragraph on the card.
   */
  blurb: string;
  image: number | Media;
  link?: {
    type?: ('reference' | 'custom' | 'none') | null;
    /**
     * Leave empty to use the page's own menu name. Fill it in only to say something different here.
     */
    label?: string | null;
    reference?: (number | null) | Page;
    /**
     * Include the protocol, e.g. https://example.com/page.
     */
    url?: string | null;
    /**
     * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  /**
   * How long it can be booked for — "A Week", "1 Month". Leave empty for a package not sold by length.
   */
  durations?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Identifies this package in the page markup. Rarely needs changing.
   */
  slug: string;
  /**
   * Low numbers first. Leave gaps so a package can be slotted in later.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guest reviews. The guest book lists them all; a page picks which to show with a testimonials block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Who wrote it.
   */
  name: string;
  quote: string;
  /**
   * Recorded, not currently shown on the site.
   */
  rating?: number | null;
  /**
   * Where it was left — "Google Reviews".
   */
  source?: string | null;
  /**
   * Identifies this review in the page markup. Rarely needs changing.
   */
  slug: string;
  /**
   * Low numbers first. Leave gaps so a review can be slotted in later.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The forms on the site, and what happens when one is sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown on the FAQs page, in the order set here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used for the link to this question — /faqs#your-slug. Changing it breaks any link already shared.
   */
  slug: string;
  /**
   * Low numbers first. Leave gaps so a question can be slotted in later.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * What people have sent through the forms on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  banner?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              target?: T;
              heading?: T;
              body?: T;
              images?: T;
              showButton?: T;
              button?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        amenities?:
          | T
          | {
              target?: T;
              heading?: T;
              subtitle?: T;
              display?: T;
              image?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        packages?:
          | T
          | {
              target?: T;
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              target?: T;
              heading?: T;
              display?: T;
              slidesToShow?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              target?: T;
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              target?: T;
              heading?: T;
              form?: T;
              asideHeading?: T;
              asideBody?: T;
              showAsideButton?: T;
              asideButton?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  navLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  label?: T;
  icon?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  blurb?: T;
  image?: T;
  link?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  durations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  rating?: T;
  source?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, logo, contact details and address. Used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  /**
   * The registered name, where it differs from the trading name.
   */
  legalName?: string | null;
  /**
   * The line that sits under the name — "An Eco-Resort at Sattal".
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  email: string;
  /**
   * Number only, no country code.
   */
  whatsapp?: string | null;
  /**
   * The label says what a caller gets — reservations, birding tours, the property manager. The same number may appear twice under different labels, as it does on the live site.
   */
  phones?:
    | {
        number: string;
        label: string;
        showInHeader?: boolean | null;
        showInFooter?: boolean | null;
        id?: string | null;
      }[]
    | null;
  address?: {
    /**
     * The one-line form the footer uses.
     */
    short?: string | null;
    locality?: string | null;
    full?: string | null;
    /**
     * Where the footer address links to — the share link for the place on a map.
     */
    mapUrl?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  social?:
    | {
        network: 'Facebook' | 'Instagram' | 'YouTube' | 'X' | 'TripAdvisor' | 'Other';
        label?: string | null;
        /**
         * The live site links these from icons with no href set.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The default description for pages that do not set their own. Around 155 characters.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The main menu, the scrolling line under it, and the search box.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Top-level items, in the order they appear.
   */
  nav?:
    | {
        link?: {
          type?: ('reference' | 'custom' | 'none') | null;
          /**
           * Leave empty to use the page's own menu name. Fill it in only to say something different here.
           */
          label?: string | null;
          reference?: (number | null) | Page;
          /**
           * Include the protocol, e.g. https://example.com/page.
           */
          url?: string | null;
          /**
           * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Leave empty for an item that navigates straight to its own destination.
         */
        children?:
          | {
              link?: {
                type?: ('reference' | 'custom' | 'none') | null;
                /**
                 * Leave empty to use the page's own menu name. Fill it in only to say something different here.
                 */
                label?: string | null;
                reference?: (number | null) | Page;
                /**
                 * Include the protocol, e.g. https://example.com/page.
                 */
                url?: string | null;
                /**
                 * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
                 */
                anchor?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The line that scrolls under the menu. Leave empty to show none. Present on every page, which is why it is here and not in a page block.
   */
  ticker?: string | null;
  showSearch?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What the bottom of every page shows. Contact details come from Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  showPhones?: boolean | null;
  showEmail?: boolean | null;
  showAddress?: boolean | null;
  /**
   * Optional. The live footer has none; add one to group links under a heading.
   */
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              link?: {
                type?: ('reference' | 'custom') | null;
                /**
                 * Leave empty to use the page's own menu name. Fill it in only to say something different here.
                 */
                label?: string | null;
                reference?: (number | null) | Page;
                /**
                 * Include the protocol, e.g. https://example.com/page.
                 */
                url?: string | null;
                /**
                 * Optional. The id of a section to jump to, without the #. Leave empty to land at the top.
                 */
                anchor?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The copyright line. Leave empty to show none. A © and the current year are added by the site.
   */
  legal?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  email?: T;
  whatsapp?: T;
  phones?:
    | T
    | {
        number?: T;
        label?: T;
        showInHeader?: T;
        showInFooter?: T;
        id?: T;
      };
  address?:
    | T
    | {
        short?: T;
        locality?: T;
        full?: T;
        mapUrl?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  social?:
    | T
    | {
        network?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ticker?: T;
  showSearch?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  showPhones?: T;
  showEmail?: T;
  showAddress?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}